const trainSchedule = {
    Monday: [
        { origin: 'GAL', destination: 'CMB', departure: '05:00 AM' },
        { origin: 'CMB', destination: 'GAL', departure: '05:45 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '05:55 AM' },
        { origin: 'JAF', destination: 'CMB', departure: '06:15 AM' },
        { origin: 'CMB', destination: 'JAF', departure: '06:35 AM' },
        { origin: 'TRI', destination: 'CMB', departure: '07:00 AM' },
        { origin: 'KDY', destination: 'CMB', departure: '08:30 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '10:30 AM' },
        { origin: 'CMB', destination: 'GAL', departure: '02:45 PM' },
        { origin: 'KDY', destination: 'CMB', departure: '04:30 PM' },
        { origin: 'CMB', destination: 'GAL', departure: '05:30 PM' },
        { origin: 'CMB', destination: 'JAF', departure: '08:15 PM' },
        { origin: 'CMB', destination: 'TRI', departure: '09:30 PM' }
    ],
    Tuesday: [
        { origin: 'GAL', destination: 'CMB', departure: '05:00 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '05:55 AM' },
        { origin: 'JAF', destination: 'CMB', departure: '06:15 AM' },
        { origin: 'CMB', destination: 'GAL', departure: '06:55 AM' },
        { origin: 'KDY', destination: 'CMB', departure: '07:10 AM' },
        { origin: 'CMB', destination: 'TRI', departure: '09:45 AM' },
        { origin: 'CMB', destination: 'JAF', departure: '11:50 AM' },
        { origin: 'GAL', destination: 'CMB', departure: '01:20 PM' },
        { origin: 'CMB', destination: 'KDY', departure: '03:30 PM' },
        { origin: 'KDY', destination: 'CMB', departure: '04:30 PM' },
        { origin: 'CMB', destination: 'GAL', departure: '05:30 PM' },
        { origin: 'TRI', destination: 'CMB', departure: '07:30 PM' }
    ],
    Wednesday: [
        { origin: 'GAL', destination: 'CMB', departure: '05:00 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '05:55 AM' },
        { origin: 'JAF', destination: 'CMB', departure: '06:15 AM' },
        { origin: 'CMB', destination: 'JAF', departure: '06:35 AM' },
        { origin: 'TRI', destination: 'CMB', departure: '07:00 AM' },
        { origin: 'KDY', destination: 'CMB', departure: '11:15 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '01:55 PM' },
        { origin: 'CMB', destination: 'GAL', departure: '02:45 PM' },
        { origin: 'KDY', destination: 'CMB', departure: '04:30 PM' },
        { origin: 'GAL', destination: 'CMB', departure: '05:45 PM' },
        { origin: 'CMB', destination: 'JAF', departure: '08:15 PM' },
        { origin: 'CMB', destination: 'TRI', departure: '09:30 PM' }
    ],
    Thursday: [
        { origin: 'GAL', destination: 'CMB', departure: '05:00 AM' },
        { origin: 'CMB', destination: 'GAL', departure: '05:45 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '05:55 AM' },
        { origin: 'JAF', destination: 'CMB', departure: '06:15 AM' },
        { origin: 'CMB', destination: 'JAF', departure: '06:35 AM' },
        { origin: 'TRI', destination: 'CMB', departure: '07:00 AM' },
        { origin: 'KDY', destination: 'CMB', departure: '08:30 AM' },
        { origin: 'CMB', destination: 'JAF', departure: '11:50 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '03:30 PM' },
        { origin: 'CMB', destination: 'GAL', departure: '05:30 PM' },
        { origin: 'GAL', destination: 'CMB', departure: '06:20 PM' },
        { origin: 'CMB', destination: 'TRI', departure: '09:30 PM' }
    ],
    Friday: [
        { origin: 'GAL', destination: 'CMB', departure: '05:00 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '05:55 AM' },
        { origin: 'JAF', destination: 'CMB', departure: '06:15 AM' },
        { origin: 'CMB', destination: 'GAL', departure: '06:55 AM' },
        { origin: 'TRI', destination: 'CMB', departure: '07:00 AM' },
        { origin: 'KDY', destination: 'CMB', departure: '08:30 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '10:30 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '01:55 PM' },
        { origin: 'CMB', destination: 'GAL', departure: '02:45 PM' },
        { origin: 'CMB', destination: 'JAF', departure: '04:15 PM' },
        { origin: 'KDY', destination: 'CMB', departure: '04:30 PM' },
        { origin: 'CMB', destination: 'GAL', departure: '05:30 PM' },
        { origin: 'CMB', destination: 'KDY', departure: '07:15 PM' },
        { origin: 'CMB', destination: 'TRI', departure: '09:30 PM' }
    ],
    Saturday: [
        { origin: 'CMB', destination: 'KDY', departure: '05:55 AM' },
        { origin: 'CMB', destination: 'JAF', departure: '06:35 AM' },
        { origin: 'CMB', destination: 'GAL', departure: '06:55 AM' },
        { origin: 'GAL', destination: 'CMB', departure: '07:30 AM' },
        { origin: 'KDY', destination: 'CMB', departure: '08:30 AM' },
        { origin: 'CMB', destination: 'TRI', departure: '09:45 AM' },
        { origin: 'CMB', destination: 'JAF', departure: '11:50 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '01:55 PM' },
        { origin: 'CMB', destination: 'GAL', departure: '02:45 PM' },
        { origin: 'KDY', destination: 'CMB', departure: '04:30 PM' },
        { origin: 'GAL', destination: 'CMB', departure: '05:00 PM' },
        { origin: 'CMB', destination: 'GAL', departure: '06:15 PM' }
    ],
    Sunday: [
        { origin: 'JAF', destination: 'CMB', departure: '06:15 AM' },
        { origin: 'TRI', destination: 'CMB', departure: '07:00 AM' },
        { origin: 'GAL', destination: 'CMB', departure: '08:15 AM' },
        { origin: 'KDY', destination: 'CMB', departure: '09:30 AM' },
        { origin: 'CMB', destination: 'JAF', departure: '11:50 AM' },
        { origin: 'CMB', destination: 'KDY', departure: '01:55 PM' },
        { origin: 'CMB', destination: 'KDY', departure: '03:30 PM' },
        { origin: 'KDY', destination: 'CMB', departure: '04:30 PM' },
        { origin: 'CMB', destination: 'GAL', departure: '05:30 PM' },
        { origin: 'GAL', destination: 'CMB', departure: '06:20 PM' },
        { origin: 'CMB', destination: 'JAF', departure: '08:15 PM' },
        { origin: 'CMB', destination: 'TRI', departure: '09:30 PM' }
    ]
};